const data = {
  data: [
    {
      No: "1",
      Queried: "booked",
      DME_booking_id: 19999,
      freight_charge: "$567",
      client_name: "Jason L",
      FP_name: "allied",
      b_date: "03/16/2021",
      connote_no: 188989,
      fp_inv_date: "06/30/2021",
      fp_inv_no: 89893,
      quoted_fp_cost: "$567",
      fp_charge_dme: "$567",
      fp_quoted_charge_cost_V: "$12",
      dme_markup: "$23",
      dme_margin: "$12",
      dme_inv_no: "11973",
      dme_inv_date: "06/30/2021",
      customer_sales_order: "",
      est_cost_pre_booking: "97",
      quoted_$_booking: "97",
      $_var_reason: "appear ...",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "9",
      $quoted: 220.13,
      $booked: 550.1
    }, 
    {
      No: "2",
      Queried: "booked",
      DME_booking_id: 19999,
      freight_charge: "$567",
      client_name: "Jason L",
      FP_name: "allied",
      b_date: "03/16/2021",
      connote_no: 188989,
      fp_inv_date: "06/30/2021",
      fp_inv_no: 89893,
      quoted_fp_cost: "$567",
      fp_charge_dme: "$567",
      fp_quoted_charge_cost_V: "$12",
      dme_markup: "$23",
      dme_margin: "$12",
      dme_inv_no: "11973",
      dme_inv_date: "06/30/2021",
      customer_sales_order: "",
      est_cost_pre_booking: "97",
      quoted_$_booking: "97",
      $_var_reason: "appear ...",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "9",
      $quoted: 220.13,
      $booked: 280.1
    }, 
    {
      No: "3",
      Queried: "booked",
      DME_booking_id: 19999,
      freight_charge: "$567",
      client_name: "Jason L",
      FP_name: "allied",
      b_date: "03/16/2021",
      connote_no: 188989,
      fp_inv_date: "06/30/2021",
      fp_inv_no: 89893,
      quoted_fp_cost: "$567",
      fp_charge_dme: "$567",
      fp_quoted_charge_cost_V: "$12",
      dme_markup: "$23",
      dme_margin: "$12",
      dme_inv_no: "11973",
      dme_inv_date: "06/30/2021",
      customer_sales_order: "",
      est_cost_pre_booking: "97",
      quoted_$_booking: "97",
      $_var_reason: "appear ...",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "9",
      $quoted: 220.13,
      $booked: 330.1
    }, 
    {
      No: "4",
      Queried: "booked",
      DME_booking_id: 19999,
      freight_charge: "$567",
      client_name: "Jason L",
      FP_name: "allied",
      b_date: "03/16/2021",
      connote_no: 188989,
      fp_inv_date: "06/30/2021",
      fp_inv_no: 89893,
      quoted_fp_cost: "$567",
      fp_charge_dme: "$567",
      fp_quoted_charge_cost_V: "$12",
      dme_markup: "$23",
      dme_margin: "$12",
      dme_inv_no: "11973",
      dme_inv_date: "06/30/2021",
      customer_sales_order: "",
      est_cost_pre_booking: "97",
      quoted_$_booking: "97",
      $_var_reason: "appear ...",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "9",
      $quoted: 500.13,
      $booked: 330.1
    }, 
    {
      No: "5",
      Queried: "booked",
      DME_booking_id: 19999,
      freight_charge: "$567",
      client_name: "Jason L",
      FP_name: "allied",
      b_date: "03/16/2021",
      connote_no: 188989,
      fp_inv_date: "06/30/2021",
      fp_inv_no: 89893,
      quoted_fp_cost: "$567",
      fp_charge_dme: "$567",
      fp_quoted_charge_cost_V: "$12",
      dme_markup: "$23",
      dme_margin: "$12",
      dme_inv_no: "11973",
      dme_inv_date: "06/30/2021",
      customer_sales_order: "",
      est_cost_pre_booking: "97",
      quoted_$_booking: "97",
      $_var_reason: "appear ...",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "9",
      $quoted: 220.13,
      $booked: 100.1
    }, 
    {
      No: "6",
      Queried: "booked",
      DME_booking_id: 19999,
      freight_charge: "$567",
      client_name: "Jason L",
      FP_name: "allied",
      b_date: "03/16/2021",
      connote_no: 188989,
      fp_inv_date: "06/30/2021",
      fp_inv_no: 89893,
      quoted_fp_cost: "$567",
      fp_charge_dme: "$567",
      fp_quoted_charge_cost_V: "$12",
      dme_markup: "$23",
      dme_margin: "$12",
      dme_inv_no: "11973",
      dme_inv_date: "06/30/2021",
      customer_sales_order: "",
      est_cost_pre_booking: "97",
      quoted_$_booking: "97",
      $_var_reason: "appear ...",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "9",
      $quoted: 100.13,
      $booked: 100.1
    }, 
    
  ]
}

export { data };